global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "whisperx-api"
    static_configs:
      - targets:
          - "whisperx-api-cuda-metrics:8000"
        labels:
          service: "whisperx-api"
          compute: "cuda"
