name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: cpu
            file: ./Dockerfile.cpu
            image: whisperx-api-server
            build_args: ""
          - target: cuda
            file: ./Dockerfile.cuda
            image: whisperx-api-server
            build_args: ""
          - target: cpu-kafka
            file: ./Dockerfile.cpu
            image: whisperx-api-server
            build_args: "EXTRA_EXTRAS=--extra kafka"
          - target: cuda-kafka
            file: ./Dockerfile.cuda
            image: whisperx-api-server
            build_args: "EXTRA_EXTRAS=--extra kafka"
          - target: worker-cpu
            file: ./Dockerfile.worker-cpu
            image: whisperx-worker
            build_args: ""
          - target: worker-cuda
            file: ./Dockerfile.worker-cuda
            image: whisperx-worker
            build_args: ""

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get package version
      id: get_version
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          VERSION="${GITHUB_REF_NAME}"
        else
          EPOCH_TIME=$(date +%s)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          VERSION="${EPOCH_TIME}-${COMMIT_HASH}"
        fi

        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Build and push ${{ matrix.target }} image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ matrix.file }}
        build-args: ${{ matrix.build_args }}
        cache-from: type=gha,scope=${{ matrix.target }}
        cache-to: type=gha,mode=max,scope=${{ matrix.target }}
        push: true
        tags: ghcr.io/nyralei/${{ matrix.image }}:${{ steps.get_version.outputs.version }}-${{ matrix.target }}
