name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Get package version
      id: get_version
      run: |
        EPOCH_TIME=$(date +%s)
        COMMIT_HASH=$(git rev-parse --short HEAD)
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        
        if [[ "$BRANCH_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          VERSION=$BRANCH_NAME
        else
          VERSION="${EPOCH_TIME}-${COMMIT_HASH}"
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: 'Build CUDA Image'
      run: |
        docker build -t ghcr.io/Nyralei/whisperx-api-server:{{ steps.get_version.outputs.version }}-cuda -f ./Dockerfile.cuda .
        docker push ghcr.io/Nyralei/whisperx-api-server:{{ steps.get_version.outputs.version }}-cuda
    - name: 'Build CPU Image'
      run: |
        docker build -t ghcr.io/Nyralei/whisperx-api-server:{{ steps.get_version.outputs.version }}-cpu -f ./Dockerfile.cpu .
        docker push ghcr.io/Nyralei/whisperx-api-server:{{ steps.get_version.outputs.version }}-cpu